/**
 * agents/lib/github.mjs
 * GitHub REST API helpers for agent-generated PRs.
 *
 * Usage:
 *   import { createAgentPR } from './lib/github.mjs';
 *   const pr = await createAgentPR({
 *     agentName: 'design-advisor',
 *     branch: 'agent/design-advisor/trust-badges',
 *     title: '[design-advisor] Add trust badge strip to homepage hero',
 *     body: '...markdown description...',
 *     files: [{ path: 'components/pages/Homepage.tsx', content: '...full file...' }],
 *   });
 *   console.log(pr.html_url);
 */

const OWNER = 'phillipwedgworth-cell';
const REPO  = 'envirocare-website';
const BASE  = 'https://api.github.com';

function headers() {
  const token = process.env.GITHUB_TOKEN;
  if (!token) throw new Error('GITHUB_TOKEN env var is not set');
  return {
    Authorization: `Bearer ${token}`,
    Accept:        'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'Content-Type': 'application/json',
    'User-Agent':   'EnviroCare-Agent/1.0',
  };
}

async function ghFetch(path, method = 'GET', body = null) {
  const res = await fetch(`${BASE}${path}`, {
    method,
    headers: headers(),
    ...(body ? { body: JSON.stringify(body) } : {}),
  });
  if (!res.ok) {
    const err = await res.text();
    throw new Error(`GitHub ${method} ${path} → ${res.status}: ${err.slice(0, 200)}`);
  }
  return res.json();
}

/** Get the SHA of the latest commit on `main`. */
async function getMainSha() {
  const data = await ghFetch(`/repos/${OWNER}/${REPO}/git/ref/heads/main`);
  return data.object.sha;
}

/** Create a branch off main. No-ops if the branch already exists. */
async function ensureBranch(branch) {
  try {
    await ghFetch(`/repos/${OWNER}/${REPO}/git/ref/heads/${branch}`);
    console.log(`[github] Branch ${branch} already exists`);
  } catch {
    const sha = await getMainSha();
    await ghFetch(`/repos/${OWNER}/${REPO}/git/refs`, 'POST', {
      ref: `refs/heads/${branch}`,
      sha,
    });
    console.log(`[github] Created branch ${branch}`);
  }
}

/** Get the current file SHA (needed to update an existing file). */
async function getFileSha(branch, filePath) {
  try {
    const data = await ghFetch(
      `/repos/${OWNER}/${REPO}/contents/${filePath}?ref=${encodeURIComponent(branch)}`
    );
    return data.sha;
  } catch {
    return null; // file doesn't exist yet
  }
}

/** Create or update a single file on the branch. */
async function upsertFile(branch, filePath, content, message) {
  const sha = await getFileSha(branch, filePath);
  const body = {
    message,
    content: Buffer.from(content).toString('base64'),
    branch,
    ...(sha ? { sha } : {}),
  };
  return ghFetch(`/repos/${OWNER}/${REPO}/contents/${filePath}`, 'PUT', body);
}

/** Ensure a label exists on the repo. */
async function ensureLabel(name, color = '0E8E40') {
  try {
    await ghFetch(`/repos/${OWNER}/${REPO}/labels/${encodeURIComponent(name)}`);
  } catch {
    try {
      await ghFetch(`/repos/${OWNER}/${REPO}/labels`, 'POST', { name, color });
    } catch { /* already exists, race condition is fine */ }
  }
}

/**
 * Full workflow: create branch → commit files → open PR → add labels.
 *
 * @param {object} opts
 * @param {string} opts.agentName    e.g. 'design-advisor'
 * @param {string} opts.branch       e.g. 'agent/design-advisor/trust-badges-20260525'
 * @param {string} opts.title        PR title
 * @param {string} opts.body         PR body (markdown)
 * @param {{ path: string, content: string, commitMsg?: string }[]} opts.files
 * @param {string[]} [opts.extraLabels]  additional labels beyond the agent label
 * @returns {Promise<{ html_url: string, number: number }>}
 */
export async function createAgentPR({ agentName, branch, title, body, files, extraLabels = [] }) {
  // 1. Create the branch
  await ensureBranch(branch);

  // 2. Commit each file
  for (const file of files) {
    const msg = file.commitMsg ?? `[${agentName}] Update ${file.path}`;
    await upsertFile(branch, file.path, file.content, msg);
    console.log(`[github] Committed ${file.path} → ${branch}`);
  }

  // 3. Open the PR
  const pr = await ghFetch(`/repos/${OWNER}/${REPO}/pulls`, 'POST', {
    title,
    body: body + `\n\n---\n🤖 Generated by \`${agentName}\` agent`,
    head: branch,
    base: 'main',
  });
  console.log(`[github] PR opened: ${pr.html_url}`);

  // 4. Apply labels
  const agentLabel  = `agent:${agentName}`;
  const agentColor  = agentName === 'design-advisor'   ? '7c3aed'
                    : agentName === 'seo-monitor'       ? '0E8E40'
                    : agentName === 'content-advisor'   ? 'f59e0b'
                    : agentName === 'site-auditor'      ? 'ef4444'
                    : agentName === 'competitor-watcher'? '3b82f6'
                    : '6b7280';

  const labels = [agentLabel, 'automated-pr', ...extraLabels];
  await Promise.all([
    ensureLabel(agentLabel, agentColor),
    ensureLabel('automated-pr', '334155'),
    ...extraLabels.map(l => ensureLabel(l)),
  ]);
  await ghFetch(`/repos/${OWNER}/${REPO}/issues/${pr.number}/labels`, 'POST', { labels });
  console.log(`[github] Labels applied: ${labels.join(', ')}`);

  return { html_url: pr.html_url, number: pr.number };
}

/**
 * Read a file from the repo main branch (for agents that need current code context).
 * Returns the decoded string content.
 */
export async function readRepoFile(filePath, ref = 'main') {
  const data = await ghFetch(
    `/repos/${OWNER}/${REPO}/contents/${filePath}?ref=${encodeURIComponent(ref)}`
  );
  return Buffer.from(data.content, 'base64').toString('utf-8');
}
