// agents/orchestrator.mjs
// Runs all agents in sequence, collects outputs, emails digest to Phillip
// Cron: weekdays 6:00 AM CT via Vercel
// Usage as Next.js API route: import from app/api/orchestrator/route.ts
// Usage as local CLI: node agents/run.mjs

import { Resend } from "resend";
import { run as runSEO } from "./seo-monitor.mjs";
import { run as runBrightLocal } from "./brightlocal.mjs";
import { logAgentRun } from "./lib/supabase.mjs";

// Lazy init — env vars not available at module load time when run via CLI
function getResend() { return new Resend(process.env.RESEND_API_KEY); }

const AGENTS = [
  { name: "SEO Monitor",  run: runSEO,         key: "seo:last-brief",        emoji: "📈" },
  { name: "BrightLocal",  run: runBrightLocal, key: "brightlocal:last-brief", emoji: "📊" },
];

async function runAll() {
  const results = [];

  for (const agent of AGENTS) {
    try {
      console.log(`[orchestrator] Running ${agent.name}…`);
      const output = await agent.run();
      results.push({ name: agent.name, emoji: agent.emoji, output, ok: true });
      await logAgentRun(agent.name, "ok", output);
      console.log(`[orchestrator] ${agent.name} done`);
    } catch (err) {
      console.error(`[orchestrator] ${agent.name} FAILED: ${err.message}`);
      const errMsg = `ERROR: ${err.message}`;
      results.push({ name: agent.name, emoji: agent.emoji, output: errMsg, ok: false });
      await logAgentRun(agent.name, "error", errMsg);
    }
  }

  return results;
}

function buildEmail(results) {
  const date = new Date().toLocaleDateString("en-US", {
    weekday: "long", month: "long", day: "numeric", year: "numeric",
  });

  const sections = results.map(r => `
<h3 style="color:${r.ok ? "#1a1a1a" : "#cc0000"};margin-bottom:4px">${r.emoji} ${r.name}${r.ok ? "" : " ⚠️"}</h3>
<pre style="font-family:inherit;white-space:pre-wrap;margin:0;padding:8px 0;border-top:1px solid #e5e5e5">${r.output}</pre>
`).join("");

  return {
    subject: `Agent Digest — ${date}`,
    html: `
<!DOCTYPE html>
<html>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:640px;margin:0 auto;padding:24px;color:#1a1a1a">
  <h2 style="margin-bottom:4px">Daily Agent Digest</h2>
  <p style="color:#666;margin-top:0">${date}</p>
  ${sections}
  <p style="color:#999;font-size:12px;margin-top:32px;border-top:1px solid #e5e5e5;padding-top:16px">
    Generated by EnviroCare agents · ${new Date().toISOString()}
  </p>
</body>
</html>`,
  };
}

export default async function handler(req, res) {
  if (req.method !== "GET" && req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  try {
    console.log("[orchestrator] Starting all agents");
    const results = await runAll();

    const { subject, html } = buildEmail(results);

    await getResend().emails.send({
      from: process.env.NOTIFY_FROM || "onboarding@resend.dev",
      to: process.env.NOTIFY_EMAIL,
      subject,
      html,
    });

    console.log("[orchestrator] Digest sent");
    return res.status(200).json({ ok: true, agents: results.map(r => ({ name: r.name, ok: r.ok })) });
  } catch (err) {
    console.error("[orchestrator] Fatal:", err.message);
    return res.status(500).json({ error: err.message });
  }
}

// Allow running the full suite directly (no email)
export { runAll };
